window.SYSTEM_QUESTIONS={
"url-shortener":{
number:2,plainTitle:"URL Shortener",title:"Design a <span>URL Shortener</span>",category:"Backend Systems",difficulty:"Intermediate",prompt:"Design a service that maps long URLs to short, durable aliases and redirects billions of reads with low latency.",concepts:["Key generation","Redirects","Caching","Sharding","Abuse prevention","Analytics"],
requirements:{note:"Keep the core redirect path tiny. Analytics and abuse detection must not slow every redirect.",functional:["Create a short URL from a valid destination","Redirect a short code to its destination","Support optional expiry and custom aliases","Record click analytics asynchronously"],nonfunctional:["Redirect P99 below 100ms","High availability; redirects are read-heavy","Short codes remain unique and durable","Prevent malicious or unsafe destinations"],assumptions:[["TRAFFIC","100M new links / month","≈39 writes/s average; design for 400/s peak"],["READ RATIO","100 redirects per write","≈4K reads/s average; 40K/s peak"],["RETENTION","5 years","≈6B URL records before expiry"],["AVAILABILITY","99.99% redirects","The read path is the product’s critical path"]]},
estimates:{items:[{label:"WRITE PEAK",value:"400/s",detail:"new aliases"},{label:"READ PEAK",value:"40K/s",detail:"redirect lookups"},{label:"CODE SPACE",value:"62⁷",detail:"≈3.5T aliases"},{label:"RAW STORAGE",value:"~3 TB",detail:"at 500 bytes / record"}],formula:"A 7-character Base62 namespace gives <b>62⁷ ≈ 3.5 trillion</b> codes—ample space, but allocation must still prevent collisions."},
naive:{title:"A map on one application server.",copy:"Generate a random code, store code → URL in a local database, and return HTTP 302 when the code is requested.",nodes:["Client","Web server","Single DB"],breaks:["The database becomes the read bottleneck","Random code generation can collide","One region adds latency worldwide","A process or database failure removes the service","Analytics writes compete with redirects"]},
evolution:[
{title:"Single redirect service",problem:"One machine owns every request and record.",explain:"Good for validating semantics, but it has a hard capacity and availability ceiling.",solution:"Persistent URL table",nodes:[["Client","network"],["App","compute"],["URL DB","storage"]]},
{title:"Separate read and write paths",problem:"Redirect traffic dwarfs link creation traffic.",explain:"Independent handlers let the hot redirect path stay minimal and scale separately.",solution:"Create API + Redirect API",nodes:[["Client","network"],["API Gateway","network"],["Create API","compute"],["Redirect API","compute"],["URL DB","storage"]]},
{title:"Cache hot codes",problem:"Popular links repeatedly read the same records.",explain:"A distributed cache absorbs skew and removes most reads from durable storage.",solution:"Redis cache",nodes:[["Client","network"],["Redirect API","compute"],["Cache","storage"],["URL DB","storage"]]},
{title:"Partition the mapping",problem:"One database cannot hold or serve the full namespace forever.",explain:"Hashing by short code spreads rows and reads evenly across shards.",solution:"Sharded URL store",nodes:[["Redirect API","compute"],["Cache","storage"],["Shard router","network"],["DB shards","storage"]]},
{title:"Allocate codes safely",problem:"Independent writers can generate the same code.",explain:"A range allocator or Snowflake-like ID service provides unique IDs without checking every random collision.",solution:"ID generator",nodes:[["Create API","compute"],["ID service","compute"],["Base62 encoder","data"],["DB shards","storage"]]},
{title:"Move side effects off-path",problem:"Analytics and safety checks inflate redirect latency.",explain:"Emit events to a durable log; consumers aggregate clicks and scan destinations independently.",solution:"Event stream",nodes:[["Redirect API","compute"],["Event log","data"],["Analytics","compute"],["Abuse scanner","compute"]]}
],
components:[
{name:"API Gateway",type:"EDGE / NETWORK",summary:"Terminates TLS, authenticates link creation, enforces quotas, and routes create versus redirect traffic.",input:"HTTPS request + route",output:"validated internal request",internals:"Normalizes headers, assigns a request ID, applies request-size limits, and chooses the correct service pool.",ops:"Run in multiple zones. Keep redirect middleware short; avoid synchronous analytics here.",without:"Every service must duplicate edge policy and abusive clients can reach expensive internals.",tradeoff:"Adds a network hop and becomes a shared policy surface that must scale carefully."},
{name:"ID Generator",type:"COORDINATION",summary:"Produces a unique numeric identifier before Base62 encoding.",input:"allocate()",output:"monotonic or unique 64-bit ID",internals:"May lease ID ranges to writers, combine timestamp/worker/sequence fields, or draw random IDs with collision checks.",ops:"Range leasing reduces coordination. Monitor clock skew for time-based schemes and never recycle active IDs.",without:"Two create workers may overwrite the same alias or require expensive retry loops.",tradeoff:"Monotonic IDs expose creation volume unless obfuscated; centralized allocation can bottleneck."},
{name:"Base62 Encoder",type:"DATA TRANSFORM",summary:"Turns an integer ID into a compact code using 0–9, a–z, and A–Z.",input:"64-bit integer",output:"7–11 character code",internals:"Repeatedly divides by 62 and maps remainders to the alphabet. Decoding reverses the operation if IDs are embedded.",ops:"Freeze the alphabet and case rules permanently. Changing them invalidates existing links.",without:"Raw numeric IDs are longer and less URL-friendly; random strings need collision handling.",tradeoff:"Deterministic sequential codes are guessable and may leak business volume."},
{name:"Redirect Cache",type:"DISTRIBUTED CACHE",summary:"Stores hot short-code mappings near redirect workers.",input:"short code",output:"destination URL or negative marker",internals:"Uses cache-aside: lookup, fetch DB on miss, populate with TTL. Negative caching limits repeated misses.",ops:"Cache immutable mappings longer; include expiry in values. Protect against hot-key overload and stampedes.",without:"Every click reaches the database, making viral links expensive and fragile.",tradeoff:"Stale entries complicate edits/deletes; capacity is finite and eviction behavior matters."},
{name:"URL Store",type:"DURABLE STORAGE",summary:"Authoritative mapping of code to destination and metadata.",input:"code, URL, owner, expiry",output:"mapping record",internals:"Primary-key lookup by code. Partition by a stable hash; use conditional insert to enforce uniqueness.",ops:"Replicate across zones, back up, checksum data, and run expiry deletion asynchronously.",without:"Links disappear after cache eviction or process restart.",tradeoff:"Cross-shard owner queries need a secondary index; replication increases write latency."},
{name:"Event Log",type:"ASYNC DATA",summary:"Decouples click recording from the latency-sensitive redirect response.",input:"click event",output:"ordered durable partitions",internals:"Partitions by code or account, batches disk writes, and lets multiple consumers maintain independent offsets.",ops:"Use at-least-once delivery and idempotent aggregators. Define retention and schema compatibility.",without:"Analytics writes slow redirects or events disappear during consumer downtime.",tradeoff:"Metrics become eventually consistent and duplicate events must be handled."},
{name:"Abuse Scanner",type:"TRUST & SAFETY",summary:"Detects phishing, malware, spam, and redirect loops.",input:"new or reported destination",output:"allow / warn / block verdict",internals:"Combines reputation lists, URL normalization, content scanning, account signals, and human review.",ops:"Scan on creation and rescan risky links asynchronously. Keep a fast blocklist in the redirect tier.",without:"The domain becomes a trusted wrapper for harmful destinations.",tradeoff:"False positives block legitimate links; deep scanning costs time and compute."}
],
deepDives:[
{title:"301 or 302 redirect?",summary:"The HTTP status changes caching, mutability, and analytics.",steps:["301 is permanent; browsers and intermediaries may cache aggressively.","302/307 preserves control at the service and keeps click visibility.","Use 307/308 when method preservation matters; normal short links are usually GET."],decision:"Default to 302/307 when destinations can change or analytics matter; use 301 only for immutable mappings."},
{title:"Unique code generation",summary:"Random, hash-based, and allocated IDs fail differently.",steps:["Random Base62 is simple but needs collision retries.","Hashing a URL makes identical destinations share codes unless salted, and collisions remain possible.","Allocated numeric IDs guarantee uniqueness before encoding and keep writes predictable."],decision:"Use leased ID ranges plus Base62 for scale; add scrambling if enumeration is a concern."},
{title:"Hot keys and viral links",summary:"One alias can exceed the normal traffic distribution.",steps:["Replicate the cached value and use client-side or proxy fan-out.","Serve immutable redirects from CDN/edge cache where policy allows.","Coalesce cache misses so one worker refreshes while others wait."],decision:"Treat popularity skew as a first-class workload, not an average-capacity problem."}
],
trace:{title:"Follow one redirect.",copy:"The hot path should finish before analytics processing begins.",steps:[["Browser","0ms",0],["Edge","8ms",8],["Rate limit","1ms",1],["Cache lookup","2ms",2],["Redirect API","1ms",1],["HTTP 302","6ms",6],["Event log","async",0]]},
failures:[{signal:"cache miss spike",title:"Cache cluster fails",effect:"Database traffic jumps by an order of magnitude.",mitigation:"Circuit-break cache, shed nonessential reads, add DB read replicas, warm replacements."},{signal:"duplicate key",title:"ID allocator overlaps ranges",effect:"Create requests conflict or, worse, overwrite mappings.",mitigation:"Fenced leases, conditional inserts, allocator epoch, collision alarm."},{signal:"replication lag",title:"Read-after-write misses",effect:"A new link returns 404 from a lagging replica.",mitigation:"Read primary briefly, sticky region, or write-through cache after creation."},{signal:"viral code",title:"One key becomes extremely hot",effect:"One cache partition or proxy saturates.",mitigation:"Local caches, replicated hot-key copies, CDN caching, request coalescing."}],
final:{copy:"Writes allocate and persist durable aliases. Reads use edge and distributed caches, then fall back to sharded storage. Side effects remain asynchronous.",primary:[["Users","network"],["DNS / CDN","network"],["Gateway","network"],["Redirect tier","compute"],["Cache","storage"],["Shard router","network"],["URL shards","storage"]],support:["Create API","ID allocator","Base62 encoder","Event log","Analytics","Abuse scanner","Metrics + tracing"],tradeoffs:[["REDIRECT STATUS","302 / 307 by default","More service control; less browser caching than 301."],["CONSISTENCY","Strong create, eventual replicas","A new code must not collide; analytics may lag."],["PARTITION KEY","hash(short_code)","Even load, but owner-based listing needs another index."]]},
interview:[["Why not hash the long URL directly?","Collisions still exist, identical URLs may need different owners/expiry, and canonicalization is subtle. A generated ID gives a clean identity."],["How do custom aliases work?","Use a conditional insert on a normalized reserved namespace, protect important words, rate-limit attempts, and define case sensitivity."],["How do links expire?","Check expiry on read, evict cache entries, and use a background sweeper or database TTL for physical deletion."],["How do you support multiple regions?","Allocate disjoint ID ranges by region, replicate mapping data, route reads locally, and define how quickly new writes appear globally."]],
quiz:[{question:"Why put click analytics on an event stream?",options:["To shorten codes","To keep redirects fast","To guarantee exactly-once clicks"],answer:1,explain:"The redirect response should not wait for aggregation or warehouse writes."},{question:"Which key best distributes URL records?",options:["Account name","Hash of short code","Creation month"],answer:1,explain:"A stable hash of the lookup key spreads point reads evenly."}],
complete:{title:"A short link is a <b>tiny distributed read system.</b>",takeaways:["Namespace sizing","Unique allocation","Cache-aside","Hot-key handling","Sharding","Async analytics","Abuse controls"]}
},
"youtube":{
number:3,plainTitle:"YouTube",title:"Design <span>YouTube</span>",category:"Media Systems",difficulty:"Advanced",prompt:"Design a global platform where creators upload video and viewers stream it reliably across devices, bandwidths, and regions.",concepts:["Chunked upload","Transcoding","Object storage","CDN","Adaptive bitrate","Metadata","Recommendations"],
requirements:{note:"Separate the upload processing plane from the low-latency playback plane.",functional:["Upload resumable videos","Transcode into multiple formats and qualities","Stream with pause, seek, and adaptive quality","Store metadata, views, likes, and comments"],nonfunctional:["Fast playback start and low rebuffering","Durable source video storage","Global delivery at massive bandwidth","Eventual consistency acceptable for view counts"],assumptions:[["UPLOADS","500 hours / minute","Source media arrives continuously"],["VIEWERS","100M daily active","Peak concurrency dominates egress"],["BITRATE","3 Mbps average","One million concurrent viewers ≈3 Tbps"],["DURABILITY","11 nines for originals","Creators cannot recreate lost source media"]]},
estimates:{items:[{label:"CONCURRENT",value:"1M",detail:"peak viewers"},{label:"EGRESS",value:"3 Tbps",detail:"at 3 Mbps avg"},{label:"UPLOAD",value:"~4 PB/day",detail:"illustrative raw video"},{label:"CHUNK",value:"2–6s",detail:"playback segment"}],formula:"Bandwidth dominates: <b>1,000,000 viewers × 3 Mbps = 3 Tbps</b>. A CDN is fundamental, not an optimization."},
naive:{title:"Upload one file and stream it from the app server.",copy:"The server saves an MP4 and returns the same bytes to every viewer.",nodes:["Creator","Web server","Disk","Viewer"],breaks:["Large uploads restart after network failure","One format does not fit every device or connection","Application servers cannot sustain video egress","Seeking requires efficient byte ranges or segments","Popular videos overload a single origin"]},
evolution:[
{title:"Store source video durably",problem:"Local disks fail and cannot scale independently.",explain:"Direct multipart upload to object storage keeps large bytes away from app servers.",solution:"Object storage",nodes:[["Creator","network"],["Upload API","compute"],["Object store","storage"]]},
{title:"Process asynchronously",problem:"Transcoding takes minutes and should not block upload completion.",explain:"A durable job queue feeds stateless media workers that retry individual renditions.",solution:"Transcode queue + workers",nodes:[["Object store","storage"],["Job queue","data"],["Transcoders","compute"],["Renditions","storage"]]},
{title:"Package adaptive streams",problem:"Bandwidth and device capabilities change during playback.",explain:"Segmented HLS/DASH manifests list multiple bitrate ladders; the player chooses per segment.",solution:"Packager + manifest",nodes:[["Renditions","storage"],["Packager","compute"],["Manifest","data"],["Player","network"]]},
{title:"Deliver from the edge",problem:"Origin bandwidth and distance cause slow starts and buffering.",explain:"CDNs cache segments near viewers and shield origin storage.",solution:"Multi-tier CDN",nodes:[["Player","network"],["Edge POP","network"],["Regional cache","storage"],["Origin","storage"]]},
{title:"Separate metadata",problem:"Titles, access policy, comments, and counts have different access patterns than media bytes.",explain:"Metadata services and databases remain small and queryable while video stays in object storage.",solution:"Metadata services",nodes:[["Client","network"],["API","network"],["Video metadata","storage"],["Engagement","data"]]},
{title:"Personalize asynchronously",problem:"The home feed requires signals from billions of interactions.",explain:"Events feed offline/nearline feature pipelines; online ranking stays latency-bounded.",solution:"Event + recommendation pipeline",nodes:[["Watch events","data"],["Event log","data"],["Feature pipeline","compute"],["Ranker","compute"],["Home feed","network"]]}
],
components:[
{name:"Upload Session Service",type:"CONTROL PLANE",summary:"Creates resumable multipart upload sessions without proxying every video byte.",input:"file metadata + creator auth",output:"signed part URLs + upload ID",internals:"Validates quota/type, chooses object key, creates multipart state, and signs time-limited storage requests.",ops:"Persist session state and completed part checksums. Expire abandoned uploads and support idempotent completion.",without:"App servers become bandwidth bottlenecks and failed uploads restart from zero.",tradeoff:"Signed URLs and multipart state complicate clients and security policy."},
{name:"Object Storage",type:"MEDIA ORIGIN",summary:"Durably stores source videos, renditions, thumbnails, captions, and manifests.",input:"immutable byte objects",output:"versioned durable objects",internals:"Erasure-codes or replicates blobs across failure domains; metadata maps keys to chunks.",ops:"Separate hot renditions from archival sources. Validate checksums and replicate source assets across regions.",without:"A disk failure loses creator content or makes playback unavailable.",tradeoff:"Object storage has higher access latency than local disk and requires lifecycle cost management."},
{name:"Transcode Orchestrator",type:"WORKFLOW",summary:"Expands one upload into a dependency graph of probe, transcode, thumbnail, caption, and packaging jobs.",input:"source-ready event",output:"idempotent media jobs",internals:"Inspects codecs/duration, selects a bitrate ladder, records job state, retries failed steps, and marks publication ready.",ops:"Use leases and idempotency keys; send poison files to a dead-letter queue; cap per-creator work.",without:"Processing is brittle, duplicated, and impossible to retry safely.",tradeoff:"Workflow state and partial completion add operational complexity."},
{name:"Transcoder",type:"MEDIA COMPUTE",summary:"Decodes source frames and emits device-compatible codecs, resolutions, and bitrates.",input:"source segment + profile",output:"encoded rendition segment",internals:"Uses CPU/GPU encoders, preserves timestamps, enforces keyframe alignment, and measures quality.",ops:"Autoscale from queue depth. Reuse segment work, checksum outputs, and isolate malformed media.",without:"Many devices cannot play uploads; one bitrate buffers on weak connections.",tradeoff:"Transcoding is compute-heavy and lossy; more renditions improve QoE but multiply cost."},
{name:"Manifest / Packager",type:"STREAMING FORMAT",summary:"Creates HLS/DASH manifests and aligned chunks for adaptive playback.",input:"encoded renditions",output:"master playlist + media segments",internals:"Aligns keyframes and segment boundaries so clients can switch quality without visible jumps.",ops:"Version manifests atomically; include captions, audio tracks, encryption keys, and content duration.",without:"Players cannot seek efficiently or adapt quality segment by segment.",tradeoff:"Short segments reduce recovery time but increase request overhead and packaging metadata."},
{name:"CDN Edge",type:"DELIVERY",summary:"Caches popular video segments close to viewers.",input:"segment URL",output:"cached bytes or origin fetch",internals:"Uses cache keys, TTLs, range requests, request coalescing, and hierarchical origin shielding.",ops:"Monitor hit ratio, origin egress, POP health, and hot objects. Use signed cookies/URLs for private media.",without:"Origin serves global bandwidth and distant viewers see slow starts and rebuffering.",tradeoff:"Cache invalidation, geographic cost, and stale policy enforcement become harder."},
{name:"Adaptive Player",type:"CLIENT ALGORITHM",summary:"Chooses the next segment quality from bandwidth, buffer, viewport, and device capability.",input:"manifest + telemetry",output:"segment requests",internals:"Estimates throughput, protects buffer occupancy, switches rendition at aligned boundaries, and recovers from errors.",ops:"Experiment carefully with startup bitrate and buffer targets. Emit QoE metrics without flooding telemetry.",without:"Playback either wastes bandwidth or buffers whenever the network changes.",tradeoff:"Aggressive quality raises visual fidelity but risks stalls; conservative quality reduces experience."},
{name:"View Counter",type:"EVENTUAL AGGREGATION",summary:"Counts valid views without synchronously updating one hot database row.",input:"qualified watch events",output:"approximate then reconciled count",internals:"Partitions events, deduplicates sessions, aggregates windows, and periodically persists totals.",ops:"Define what counts as a view. Reconcile late events and detect bots/fraud.",without:"A viral video creates a write hotspot or every playback waits on a counter update.",tradeoff:"Displayed counts lag and may be approximate."}
],
deepDives:[
{title:"Adaptive bitrate selection",summary:"The player makes a repeated control decision, not one startup choice.",steps:["Fetch a small initial segment at a safe bitrate.","Estimate sustainable throughput and inspect current buffer.","Choose the highest rendition below a safety fraction of bandwidth.","Drop quickly on buffer risk; climb cautiously to avoid oscillation."],decision:"Optimize for rebuffering and startup time before raw resolution."},
{title:"Transcoding idempotency",summary:"Workers will retry; outputs must not multiply or corrupt publication.",steps:["Derive job IDs from video, rendition, segment, and pipeline version.","Write to a temporary object and validate checksum/duration.","Commit output atomically and treat an existing valid object as success.","Publish the manifest only after required renditions are complete."],decision:"At-least-once jobs plus deterministic output keys are simpler than chasing exactly-once execution."},
{title:"CDN cache hierarchy",summary:"A miss at every edge can still crush the origin.",steps:["Viewer requests nearest edge POP.","Edge miss goes to a regional shield rather than directly to storage.","Shield coalesces simultaneous misses for the same segment.","Immutable hashed URLs allow long TTLs and safe caching."],decision:"Use immutable segment URLs and origin shielding to turn popularity into cache efficiency."}
],
trace:{title:"Follow one playback start.",copy:"Startup latency spans metadata, manifest, segment selection, and edge delivery.",steps:[["Player","tap",0],["Metadata API","18ms",18],["Manifest CDN","14ms",14],["ABR select","2ms",2],["Edge segment","28ms",28],["Decode","16ms",16],["First frame","78ms",0]]},
failures:[{signal:"queue age rising",title:"Transcoder backlog",effect:"Uploads remain processing for hours.",mitigation:"Autoscale profiles separately, prioritize recent/premium jobs, degrade bitrate ladder."},{signal:"origin egress spike",title:"CDN cache purge or miss storm",effect:"Storage and network saturate.",mitigation:"Origin shields, request coalescing, rate limits, pre-warm predictable launches."},{signal:"segment 404",title:"Manifest published too early",effect:"Playback stalls on missing rendition chunks.",mitigation:"Atomic publication marker; validate every referenced object before publish."},{signal:"rebuffer ratio",title:"Bad ABR release",effect:"Clients choose quality above sustainable bandwidth.",mitigation:"Feature flag, client fallback policy, QoE alert, fast rollback."}],
final:{copy:"Control-plane APIs manage uploads and metadata. A durable asynchronous media pipeline produces immutable streams. Playback bytes flow through CDN edges, not application servers.",primary:[["Creators","network"],["Upload sessions","compute"],["Object origin","storage"],["Job queue","data"],["Transcode fleet","compute"],["Packager","compute"],["CDN","network"],["Viewers","network"]],support:["Metadata DB","Search index","Event log","Recommendation ranker","Rights / DRM","QoE telemetry","Moderation"],tradeoffs:[["SEGMENT SIZE","2–6 seconds","Shorter adapts faster; longer reduces request overhead."],["CONSISTENCY","Strong publication marker","Counts and recommendations may be eventually consistent."],["CODEC LADDER","Device + bandwidth coverage","More formats improve reach but multiply compute/storage."]]},
interview:[["Why not stream from the application server?","Video bandwidth dwarfs API traffic. Object storage plus CDN provides cheap durable bytes and global edge capacity."],["How does seeking work?","The player maps time to independently decodable segments or byte ranges, then requests from the closest keyframe."],["How do you prevent creator loss?","Durably confirm multipart completion, checksum the source, replicate before acknowledging publication, and retain originals under lifecycle policy."],["Where does recommendation fit?","Watch events feed offline/nearline features; candidate generation narrows millions of videos; online ranking meets a strict feed latency budget."]],
quiz:[{question:"Why must renditions align keyframes?",options:["To encrypt comments","To switch quality cleanly","To count views"],answer:1,explain:"The player can change bitrate at segment boundaries only when decoding can restart consistently."},{question:"What protects origin during a viral launch?",options:["More metadata rows","Origin shield + CDN","Larger app server"],answer:1,explain:"Hierarchical caches coalesce misses and serve bytes near viewers."}],
complete:{title:"Video scale is a <b>media pipeline plus an edge network.</b>",takeaways:["Resumable upload","Async transcoding","ABR streaming","Immutable segments","CDN hierarchy","QoE metrics","Eventual counters"]}
},
"whatsapp":{
number:4,plainTitle:"WhatsApp",title:"Design <span>WhatsApp</span>",category:"Messaging Systems",difficulty:"Advanced",prompt:"Design real-time one-to-one and group messaging with offline delivery, multi-device sync, ordering, and end-to-end encryption.",concepts:["WebSockets","Message ordering","Offline inbox","Fanout","Presence","Encryption","Multi-device"],
requirements:{note:"Message delivery and privacy are core; presence and read receipts can degrade gracefully.",functional:["Send one-to-one and group messages","Deliver after recipients reconnect","Sync multiple devices","Support sent, delivered, and read states"],nonfunctional:["Low online delivery latency","Durable messages until acknowledged","Per-conversation ordering","End-to-end encrypted content"],assumptions:[["USERS","2B registered","Hundreds of millions concurrently connected"],["MESSAGES","100B / day","≈1.2M/s average; several million/s peak"],["PAYLOAD","~1 KB median","Media travels through separate object storage"],["CONNECTIONS","500M live","Connection state must be partitioned"]]},
estimates:{items:[{label:"AVG RATE",value:"1.2M/s",detail:"messages"},{label:"PEAK RATE",value:"5M/s",detail:"design target"},{label:"DAILY DATA",value:"100 TB",detail:"at 1 KB each"},{label:"LIVE SOCKETS",value:"500M",detail:"partitioned gateways"}],formula:"The hard problem is not one payload; it is <b>millions of ordered writes plus hundreds of millions of long-lived connections</b>."},
naive:{title:"One WebSocket server forwards messages.",copy:"Both clients connect to a server. It forwards the message directly if the recipient is online.",nodes:["Sender","Socket server","Recipient"],breaks:["Offline recipients lose messages","A server restart drops connection location","Concurrent sends reorder across workers","Group fanout overloads one process","Multiple devices diverge"]},
evolution:[
{title:"Persistent connections",problem:"Polling wastes bandwidth and delays delivery.",explain:"Connection gateways hold WebSockets and send bidirectional events.",solution:"Gateway fleet",nodes:[["Sender","network"],["Gateway","network"],["Recipient","network"]]},
{title:"Durable message acceptance",problem:"The recipient may be offline or a gateway may fail.",explain:"Persist an encrypted envelope before acknowledging sent status.",solution:"Message log",nodes:[["Gateway","network"],["Message service","compute"],["Durable log","data"]]},
{title:"Locate online devices",problem:"Any device may connect to any gateway.",explain:"A sharded session directory maps device IDs to current connection workers.",solution:"Session directory",nodes:[["Message service","compute"],["Session directory","storage"],["Gateway shard","network"]]},
{title:"Offline inboxes",problem:"A message must wait through hours of disconnection.",explain:"Per-device queues retain undelivered envelopes until device acknowledgement.",solution:"Inbox store",nodes:[["Durable log","data"],["Fanout","compute"],["Device inbox","storage"],["Gateway","network"]]},
{title:"Group fanout",problem:"Large groups multiply one logical send into many device deliveries.",explain:"Async fanout partitions membership and writes device inbox references with backpressure.",solution:"Group fanout workers",nodes:[["Group service","compute"],["Membership store","storage"],["Fanout workers","compute"],["Inboxes","storage"]]},
{title:"Multi-device encrypted sync",problem:"Each user can have several independent encryption identities and delivery cursors.",explain:"Encrypt an envelope per recipient device and track acknowledgements per device.",solution:"Device key + sync service",nodes:[["Key directory","storage"],["Message service","compute"],["Device envelopes","data"],["Sync cursors","storage"]]}
],
components:[
{name:"Connection Gateway",type:"REAL-TIME EDGE",summary:"Maintains millions of authenticated WebSocket sessions and pushes events to connected devices.",input:"socket frames + internal delivery",output:"client events + acknowledgements",internals:"Authenticates device tokens, heartbeats connections, applies frame limits, and maps a socket to a device session.",ops:"Use event-loop workers, connection draining, heartbeat timeouts, and consistent routing. Keep business logic elsewhere.",without:"Clients poll repeatedly and the system cannot push low-latency messages.",tradeoff:"Long-lived connections make deploys, load balancing, and capacity planning stateful."},
{name:"Session Directory",type:"EPHEMERAL STATE",summary:"Maps device IDs to the gateway currently holding their live connection.",input:"connect / heartbeat / disconnect",output:"gateway route or offline",internals:"Stores short-lived leases rather than permanent presence. Generation numbers prevent stale disconnects removing a newer session.",ops:"Shard by device ID, expire aggressively, and rebuild from gateways after failure.",without:"The delivery service cannot find the online recipient and must broadcast or treat everyone offline.",tradeoff:"Lease churn is enormous; stale entries cause failed pushes and retries."},
{name:"Message Service",type:"ORDERING + DURABILITY",summary:"Validates encrypted envelopes, assigns IDs and conversation sequence, then durably accepts them.",input:"encrypted message envelope",output:"message ID + sent acknowledgement",internals:"Uses an idempotency key for retries, verifies membership, selects a partition, and appends before ACK.",ops:"Partition by conversation for local ordering. Detect hot conversations and cap payload size.",without:"Retries duplicate messages and crashes lose accepted sends.",tradeoff:"Ordering by conversation can create hot partitions for enormous groups."},
{name:"Durable Message Log",type:"APPEND-ONLY DATA",summary:"Buffers accepted messages between ingress and recipient fanout.",input:"ordered message records",output:"partitioned consumer stream",internals:"Replicates append-only segments and maintains consumer offsets for fanout, abuse, and metrics.",ops:"At-least-once delivery requires idempotent inbox writes. Retain until all required downstream consumers are safe.",without:"Fanout outages back up senders or lose messages.",tradeoff:"Delivery is asynchronous and duplicates can occur during retries."},
{name:"Device Inbox",type:"OFFLINE DELIVERY",summary:"Stores references or encrypted envelopes not yet acknowledged by a specific device.",input:"device ID + message ID",output:"ordered pending page",internals:"Maintains a cursor/sequence, supports pagination on reconnect, and deletes after durable device acknowledgement.",ops:"Compact acknowledged ranges; expire according to policy; bound malicious senders and huge offline backlogs.",without:"Offline and temporarily disconnected users miss messages.",tradeoff:"Per-device duplication increases writes and storage, especially with many linked devices."},
{name:"Group Membership Service",type:"SOCIAL GRAPH",summary:"Authoritatively answers who may send and which users/devices should receive a group message.",input:"group ID + membership mutation/query",output:"versioned member set",internals:"Uses a membership version so fanout has a consistent snapshot and permission checks are auditable.",ops:"Cache small groups; paginate huge groups; serialize admin changes per group.",without:"Removed users may receive messages or valid members may be skipped.",tradeoff:"Strong membership checks add latency; cached membership can be stale."},
{name:"Key Directory",type:"CRYPTOGRAPHIC METADATA",summary:"Publishes device identity keys and one-time prekeys; servers route ciphertext without plaintext access.",input:"device registration / key lookup",output:"signed public key bundle",internals:"Verifies device identity, consumes one-time prekeys, and records key changes for user-visible safety alerts.",ops:"Protect key replacement with strong authentication and transparency/auditing. Never log private keys.",without:"Clients cannot establish end-to-end encrypted sessions securely.",tradeoff:"Key rotation and multi-device identity create complex UX and recovery paths."},
{name:"Receipt Aggregator",type:"EPHEMERAL EVENTS",summary:"Aggregates delivered/read acknowledgements without blocking core message delivery.",input:"device receipt ranges",output:"conversation receipt updates",internals:"Compresses contiguous sequence ranges and computes user-level status from per-device acknowledgements.",ops:"Batch and rate-limit receipts; allow eventual consistency; drop low-value typing events first under load.",without:"Senders never know delivery state, but message content still works.",tradeoff:"Exact per-device receipts create high write amplification and privacy implications."}
],
deepDives:[
{title:"Per-conversation ordering",summary:"Global order is expensive and unnecessary.",steps:["Route a conversation ID to one logical partition.","Assign a monotonically increasing conversation sequence at durable append.","Clients buffer brief gaps and request missing ranges.","Across independent conversations, allow arbitrary interleaving."],decision:"Guarantee order within a conversation, not across the entire service."},
{title:"At-least-once delivery",summary:"Network acknowledgements can be lost even when writes succeeded.",steps:["Client assigns an idempotency key before send.","Server stores key → message ID with the durable append.","Retries return the existing message ID instead of appending again.","Device inbox deduplicates by message ID."],decision:"Use idempotency and deduplication; exactly-once end-to-end delivery is not a realistic primitive."},
{title:"Group fanout strategy",summary:"Fanout-on-write and fanout-on-read trade send cost for read complexity.",steps:["Small groups: copy references to device inboxes for fast reads.","Very large broadcast groups: retain one group log and let devices read by cursor.","Partition member expansion and apply backpressure.","Respect membership version at send time."],decision:"Use a hybrid threshold; no single fanout strategy fits both families and million-member channels."}
],
trace:{title:"Follow one encrypted message.",copy:"The server can route metadata and ciphertext without reading message content.",steps:[["Sender encrypts","3ms",3],["Gateway","8ms",8],["Message log","12ms",12],["Fanout","4ms",4],["Inbox","6ms",6],["Recipient push","9ms",9],["Delivered ACK","8ms",8]]},
failures:[{signal:"heartbeat timeout",title:"Gateway dies",effect:"Thousands of sockets disconnect together.",mitigation:"Clients reconnect with jitter; session leases expire; resume inbox cursor."},{signal:"consumer lag",title:"Fanout falls behind",effect:"Sent ACKs succeed but recipient delivery is delayed.",mitigation:"Scale consumers, prioritize direct chats, bound groups, expose delayed state."},{signal:"duplicate ACK",title:"Network retry duplicates send",effect:"Recipient may see repeated content.",mitigation:"Client idempotency key and dedupe at append/inbox/client."},{signal:"hot partition",title:"Huge group spikes",effect:"One conversation partition saturates.",mitigation:"Subpartition fanout work while preserving one accepted sequence log."}],
final:{copy:"Gateways own connections, not messages. The durable message service owns acceptance and per-conversation order. Async fanout and device inboxes make recipients independent of sender availability.",primary:[["Sender devices","network"],["Socket gateways","network"],["Message service","compute"],["Message log","data"],["Fanout workers","compute"],["Device inboxes","storage"],["Recipient gateways","network"]],support:["Session directory","Group membership","Key directory","Media object store","Push notifications","Receipt aggregator","Abuse controls"],tradeoffs:[["DELIVERY","At least once + dedupe","Retries are safe without impossible exactly-once claims."],["ORDER","Per conversation","Avoids a global sequencer and matches user expectations."],["GROUP FANOUT","Hybrid by group size","Small groups favor write fanout; huge channels favor shared logs."]]},
interview:[["How does offline delivery work?","After durable acceptance, fanout writes each device inbox. Reconnecting devices request entries after their acknowledged cursor."],["How do push notifications fit?","When no live gateway route exists, a notification worker sends a minimal wake-up via APNs/FCM; the device then fetches encrypted inbox data."],["Can the server search encrypted messages?","Not normally without weakening E2EE. Client-side indexes can search locally; server features must be designed around encrypted metadata limits."],["How do read receipts work across devices?","Track per-device delivered/read sequence ranges, then aggregate into a user-visible state according to product semantics."]],
quiz:[{question:"What should be ordered globally?",options:["All messages","Messages in one conversation","All user logins"],answer:1,explain:"Conversation-local order meets UX needs without a global bottleneck."},{question:"Why keep a per-device inbox?",options:["For video transcoding","For offline delivery and multi-device cursors","To generate encryption keys"],answer:1,explain:"Each device can be offline and acknowledge independently."}],
complete:{title:"Messaging is <b>durable ordered delivery</b> over unreliable connections.",takeaways:["WebSocket gateways","Conversation ordering","Idempotency","Offline inboxes","Hybrid fanout","Device keys","Receipt aggregation"]}
},

"netflix":{number:5,plainTitle:"Netflix",title:"Design <span>Netflix</span>",category:"Streaming Systems",difficulty:"Advanced",prompt:"Design a global subscription video service with personalized discovery, protected media, adaptive playback, and resilient regional control planes.",concepts:["Open Connect","DRM","Encoding ladder","Playback authorization","Personalization","Regional failover"],
requirements:{note:"This design emphasizes licensed catalogs, device certification, DRM, and predictable title launches.",functional:["Browse a personalized regional catalog","Authorize subscription and content rights","Resume playback across devices","Stream adaptive protected video"],nonfunctional:["Fast playback start and low rebuffering","Regional control-plane resilience","Global delivery at extreme bandwidth","Protect licensed media"],assumptions:[["MEMBERS","300M households","Multiple profiles and devices"],["CONCURRENCY","20M peak streams","Evening peaks correlate by geography"],["BITRATE","5 Mbps average","≈100 Tbps at peak"],["CATALOG","20K titles / region","Rights vary by place and time"]]},
estimates:{items:[{label:"PEAK STREAMS",value:"20M",detail:"concurrent"},{label:"EGRESS",value:"100 Tbps",detail:"global"},{label:"START SLO",value:"<2s",detail:"first frame"},{label:"AVAILABILITY",value:"99.99%",detail:"playback start"}],formula:"At <b>20M streams × 5 Mbps = 100 Tbps</b>, placing content inside ISP networks is architectural."},
naive:{title:"A catalog API and one central video origin.",copy:"Users browse titles from a database and stream one encoded file from central object storage.",nodes:["TV app","Catalog API","Origin"],breaks:["Central egress cannot serve global peak","One encoding fails varied networks","Rights and subscription checks are absent","A regional outage blocks playback start","Popular releases synchronize demand"]},
evolution:[
{title:"Separate browse and playback",problem:"Metadata and multi-gigabyte media need different paths.",explain:"APIs return metadata and authorization; media bytes bypass them.",solution:"Control + data planes",nodes:[["App","network"],["API","compute"],["Metadata","storage"],["Origin","storage"]]},
{title:"Encode a quality ladder",problem:"Networks and screens vary widely.",explain:"Per-title encoding emits aligned bitrate/resolution representations.",solution:"Encoding pipeline",nodes:[["Master","storage"],["Encoder","compute"],["Segments","storage"]]},
{title:"Protect playback",problem:"Licensed content needs entitlement, territory, and DRM.",explain:"Playback issues short-lived manifest and license context after authorization.",solution:"Playback auth + DRM",nodes:[["App","network"],["Playback API","compute"],["Entitlement","data"],["DRM","compute"]]},
{title:"Place media near members",problem:"Central delivery remains costly at predictable scale.",explain:"ISP appliances receive popular encrypted segments before peaks.",solution:"Open Connect edge",nodes:[["Origin","storage"],["Fill service","compute"],["ISP edge","network"],["TV","network"]]},
{title:"Personalize discovery",problem:"A static catalog makes discovery difficult.",explain:"Offline features and online ranking assemble rows per profile.",solution:"Recommendation stack",nodes:[["Events","data"],["Features","storage"],["Candidates","compute"],["Ranker","compute"]]},
{title:"Survive regional failure",problem:"Playback cannot depend on one control region.",explain:"Replicate entitlement state and fail over stateless services.",solution:"Multi-region control plane",nodes:[["Global route","network"],["Region A","compute"],["Region B","compute"],["Replicated state","storage"]]}
],
components:[
{name:"Catalog Service",type:"METADATA",summary:"Returns only titles available for the profile’s region, maturity setting, and device.",input:"profile + territory + device",output:"available localized titles",internals:"Joins title metadata, rights windows, localization, maturity policy, and device capability.",ops:"Cache versioned regional slices; propagate rights changes quickly.",without:"Users see unavailable content or miss entitled titles.",tradeoff:"Caching improves latency but can serve stale rights."},
{name:"Playback Service",type:"SESSION CONTROL",summary:"Creates a short-lived authorized playback session.",input:"account + title + device",output:"signed manifest + DRM context",internals:"Checks subscription, concurrent streams, territory, title window, codec support, and fraud signals.",ops:"Run multi-region, make requests idempotent, audit decisions, and use short TTLs.",without:"Anyone with a URL could bypass subscription and policy.",tradeoff:"Synchronous policy checks add startup latency."},
{name:"Per-title Encoder",type:"MEDIA COMPUTE",summary:"Selects an efficient bitrate ladder from the visual complexity of each title.",input:"mezzanine master",output:"aligned encoded ladder",internals:"Encodes candidates, measures perceptual quality, and chooses resolution/bitrate points.",ops:"Version recipes, validate audio/subtitles, and retain masters for future codecs.",without:"A fixed ladder wastes bandwidth or loses quality.",tradeoff:"Analysis costs compute and delays publication."},
{name:"Manifest Service",type:"PLAYBACK METADATA",summary:"Builds the exact stream map allowed for this device and session.",input:"session + capabilities",output:"signed adaptive manifest",internals:"Filters codecs, audio, subtitles, regional variants, and references encrypted segments.",ops:"Keep manifests small and short-lived; bind them to session policy.",without:"The player cannot select compatible media or enforce authorization.",tradeoff:"Personalized manifests reduce cache reuse."},
{name:"DRM License Service",type:"CONTENT PROTECTION",summary:"Issues decryption licenses to attested authorized devices.",input:"license challenge + token",output:"time-bound wrapped key",internals:"Checks device security level and wraps keys for Widevine, PlayReady, or FairPlay.",ops:"Keep keys in HSMs, rate-limit, and deploy redundant regional license endpoints.",without:"Protected segments cannot play or keys must be exposed insecurely.",tradeoff:"Adds startup calls and device-specific failures."},
{name:"ISP Edge Appliance",type:"CONTENT DELIVERY",summary:"Serves encrypted segments from inside or near the access network.",input:"segment request",output:"local immutable bytes",internals:"Stores predicted popular objects, verifies hashes, and fetches misses through a hierarchy.",ops:"Monitor inventory, disks, hit ratio, and fill links; pre-position launches.",without:"Streams cross costly transit and distant origin paths.",tradeoff:"Prediction mistakes waste disk; fleet operations are complex."},
{name:"Recommendation Ranker",type:"ONLINE ML",summary:"Scores candidate titles for a profile under a strict browse latency budget.",input:"candidates + features",output:"ordered rows",internals:"Combines models, diversity, freshness, business rules, and artwork selection.",ops:"Fallback to popular rows; log exposures; shadow and canary model changes.",without:"Members struggle to discover content.",tradeoff:"Personalization complicates caching and creates feedback loops."}
],
deepDives:[
{title:"Playback authorization",summary:"A URL is not proof of entitlement.",steps:["Authenticate account/profile.","Check subscription, stream limit, territory, rights window, and device.","Issue short-lived signed manifest.","Issue DRM license bound to the session."],decision:"Keep durable entitlement separate from short-lived playback sessions."},
{title:"Content placement",summary:"Demand is predictable enough to pre-fill much of the catalog.",steps:["Forecast popularity by region/ISP/time.","Fill appliances off-peak.","Verify immutable objects with hashes.","Use hierarchical origin fallback for misses."],decision:"Pre-position the hot catalog and hierarchically fill the tail."},
{title:"Graceful browse degradation",summary:"Playback should survive recommendation trouble.",steps:["Cache last-known personal rows.","Prepare regional popular and genre fallbacks.","Keep playback independent of ranking.","Drop artwork experiments before core rows."],decision:"Degrade discovery quality before playback availability."}
],
trace:{title:"Follow one playback start.",copy:"The control plane authorizes; the edge data plane delivers.",steps:[["TV app","play",0],["Gateway","12ms",12],["Entitlement","18ms",18],["Manifest","16ms",16],["DRM","28ms",28],["ISP edge","42ms",42],["First frame","116ms",0]]},
failures:[{signal:"regional 5xx",title:"Control region fails",effect:"Browse and new playback fail locally.",mitigation:"Global failover, replicated entitlement, cached home rows."},{signal:"edge miss rate",title:"Appliance loses content",effect:"Transit spikes and startup slows.",mitigation:"Hierarchical fill, parent cache, origin reserve."},{signal:"license latency",title:"DRM is impaired",effect:"Segments arrive but cannot decode.",mitigation:"Multi-region license service, HSM redundancy, bounded retry."},{signal:"rights mismatch",title:"Catalog policy is stale",effect:"Unavailable content appears.",mitigation:"Versioned rights events and authoritative playback check."}],
final:{copy:"Browse and playback control run in replicated regions. Encoded encrypted media is placed in ISP edges and never flows through business APIs.",primary:[["Member app","network"],["Global gateway","network"],["Playback","compute"],["Entitlement","data"],["Manifest + DRM","compute"],["ISP edge","network"],["Player","network"]],support:["Catalog","Recommendations","Encoding pipeline","Object origin","Placement service","Telemetry","Accounts"],tradeoffs:[["EDGE","Predict + pre-fill","Saves transit; can waste storage."],["RIGHTS","Authoritative at play","Browse may cache; playback rechecks."],["DEGRADE","Popular-row fallback","Discovery quality drops before playback."]]},
interview:[["How is Netflix different from YouTube?","Licensed catalog, per-title encoding, DRM, entitlement, and predictable launches are more central."],["Why appliances inside ISPs?","Video peak is enormous and localized; in-network delivery reduces transit and latency."],["Can an old manifest be replayed?","Bind signed URLs and licenses to short-lived sessions and device policy."],["If recommendations fail?","Return cached personal or regional fallback rows; keep playback independent."]],
quiz:[{question:"When ranking fails, what should happen?",options:["Stop playback","Serve fallback rows","Delete catalog"],answer:1,explain:"Discovery can degrade while playback stays available."},{question:"Why recheck rights at playback?",options:["Browse cache may be stale","To sharpen pixels","To count subtitles"],answer:0,explain:"Playback is the authoritative security boundary."}],
complete:{title:"Streaming is <b>content placement plus protected control.</b>",takeaways:["Playback sessions","Entitlement","DRM","Per-title encoding","ISP edge","Regional failover","Graceful browse"]}
},

"uber-nearby":{number:6,plainTitle:"Uber Nearby Drivers",title:"Design <span>Uber Nearby Drivers</span>",category:"Geo-distributed Systems",difficulty:"Advanced",prompt:"Design the real-time location and matching system that finds available drivers near a rider, ranks them, and reserves one safely.",concepts:["Geospatial index","Location stream","Cell partitioning","ETA","Matching","Leases","Hotspots"],
requirements:{note:"Nearby search is approximate filtering; dispatch must confirm availability atomically.",functional:["Drivers publish location and availability","Riders query nearby eligible drivers","Rank by ETA and marketplace rules","Reserve one driver for one trip"],nonfunctional:["Location freshness under five seconds","Nearby query below 100ms","No double dispatch","Survive city hotspots"],assumptions:[["DRIVERS","5M online peak","Updates every 3 seconds"],["LOCATION RATE","~1.7M/s","Write-heavy ephemeral state"],["REQUESTS","100K/s peak","Airports create skew"],["FRESHNESS","<5 seconds","Old positions expire"]]},
estimates:{items:[{label:"LOCATION",value:"1.7M/s",detail:"5M ÷ 3s"},{label:"SEARCH",value:"100K/s",detail:"peak"},{label:"POSITION",value:"~100 B",detail:"latest state"},{label:"TTL",value:"5–10s",detail:"stale removal"}],formula:"Driver telemetry dominates: <b>5,000,000 ÷ 3 seconds ≈ 1.7M location updates/s</b>."},
naive:{title:"Scan every driver row by latitude and longitude.",copy:"Drivers update one table; riders run a radius query and sort by straight-line distance.",nodes:["Drivers","SQL geo table","Rider"],breaks:["Millions of updates contend","Radius scans become expensive","Straight-line distance gives poor ETA","Stale drivers stay visible","Two riders select the same driver"]},
evolution:[
{title:"Stream driver updates",problem:"Synchronous DB writes cannot absorb bursts.",explain:"Gateways validate and append location events.",solution:"Location event log",nodes:[["Drivers","network"],["Gateway","network"],["Stream","data"]]},
{title:"Keep only latest state",problem:"Search needs current position, not history.",explain:"Consumers materialize one expiring record per driver.",solution:"Latest-location store",nodes:[["Stream","data"],["Updater","compute"],["Driver state","storage"]]},
{title:"Index by cells",problem:"Scanning every driver is impossible.",explain:"Map coordinates to hierarchical cells with available-driver sets.",solution:"Geo cell index",nodes:[["Driver state","storage"],["Cell index","data"],["Query","compute"]]},
{title:"Expand rings adaptively",problem:"Dense and sparse areas need different radii.",explain:"Search neighboring cells until enough candidates or budget ends.",solution:"Ring search",nodes:[["Rider","network"],["Nearby service","compute"],["Cell rings","data"]]},
{title:"Rank by ETA",problem:"Nearest geometrically may be far by roads.",explain:"A routing service scores a bounded candidate set.",solution:"ETA service",nodes:[["Candidates","data"],["ETA batch","compute"],["Ranker","compute"]]},
{title:"Reserve atomically",problem:"Concurrent requests can choose one driver.",explain:"Dispatch compare-and-sets a short driver lease.",solution:"Dispatch reservation",nodes:[["Ranked IDs","data"],["Dispatch","compute"],["Driver lease","storage"],["Offer","network"]]}
],
components:[
{name:"Location Gateway",type:"MOBILE INGESTION",summary:"Authenticates drivers and absorbs millions of tiny GPS messages.",input:"driver, lat/lon, heading, speed, sequence",output:"normalized location event",internals:"Rejects impossible jumps, deduplicates sequence, adds receive time, and selects a stream partition.",ops:"Use regional persistent connections, quotas, validation, and backpressure.",without:"Invalid and out-of-order client data floods state stores.",tradeoff:"Validation can discard real GPS anomalies."},
{name:"Event Stream",type:"HIGH-RATE LOG",summary:"Decouples mobile writes from indexing, fraud, trip tracking, and history consumers.",input:"normalized location",output:"ordered per-driver events",internals:"Partitions by driver ID so each driver stays ordered while the fleet scales horizontally.",ops:"Keep short hot retention; archive trip paths separately; monitor consumer lag.",without:"All consumers must synchronously accept full write rate.",tradeoff:"Indexes see updates after small lag and handle replay."},
{name:"Latest Driver Store",type:"EPHEMERAL STATE",summary:"Stores the newest position, session, product, and availability per driver.",input:"ordered events",output:"driver state by ID",internals:"Applies only newer generations/sequences and attaches a renewable expiry lease.",ops:"Distribute in-memory across zones; reconcile periodically from active sessions.",without:"Queries fold event history and offline drivers persist.",tradeoff:"Not a historical source and may briefly trail the log."},
{name:"Geo Cell Index",type:"SPATIAL INDEX",summary:"Maps a hierarchical cell to currently eligible driver IDs.",input:"old/new cell + availability",output:"cell → driver set",internals:"Moves membership on cell changes and supports parent/neighbor resolution.",ops:"Shard by city and cell, split hot cells, repair from latest-state snapshots.",without:"Each query scans millions of drivers.",tradeoff:"Boundaries add neighbor reads; crossings add write churn."},
{name:"Nearby Query",type:"CANDIDATE GENERATION",summary:"Returns a bounded fresh set around the pickup.",input:"pickup + product",output:"candidate IDs",internals:"Searches the containing cell then neighboring rings, filters TTL/product, and stops on count/deadline.",ops:"Hard-limit expansion and cache cell topology—not fast-changing results.",without:"Matcher cannot narrow the fleet within latency.",tradeoff:"A bounded search may omit a farther better driver."},
{name:"ETA Service",type:"ROUTING",summary:"Estimates road travel time from candidates to pickup.",input:"pickup + positions",output:"ETA per candidate",internals:"Snaps to roads, applies traffic weights, and runs batched one-to-many routing or approximation.",ops:"Approximate first, precise top-N second; cache traffic/road tiles.",without:"Distance fails across rivers, highways, and one-way roads.",tradeoff:"Accuracy costs compute and traffic data ages."},
{name:"Dispatch Coordinator",type:"CONSISTENCY BOUNDARY",summary:"Reserves one driver and owns offer/accept/timeout transitions.",input:"ranked candidates + ride",output:"one active offer",internals:"CASes AVAILABLE → RESERVED(ride, expiry, fence), then advances on rejection.",ops:"Persist state machine, use idempotency and fencing tokens.",without:"One driver can be promised to multiple riders.",tradeoff:"Strong coordination adds latency at the final step."}
],
deepDives:[
{title:"Adaptive geo cells",summary:"One global resolution cannot fit downtown and rural areas.",steps:["Encode points into hierarchical cells.","Use fine cells in dense areas and parents in sparse ones.","Always include neighbors at boundaries.","Split hot cells into logical subshards."],decision:"Choose adaptive hierarchy from observed drivers per cell and query cost."},
{title:"Out-of-order GPS",summary:"Mobile updates arrive late and duplicated.",steps:["Assign session generation and monotonic sequence.","Apply only newer generation/sequence.","Use server time for TTL and device time for motion.","Expire the lease on missing heartbeat."],decision:"Freshness is a renewable lease, not a permanent flag."},
{title:"Prevent double dispatch",summary:"Search can be eventual; reservation cannot.",steps:["Query returns candidates without locks.","Dispatch conditionally reserves the top driver.","Lease includes ride, expiry, and fencing version.","Release only if the same fence still owns it."],decision:"Use strong consistency only at the narrow reservation boundary."}
],
trace:{title:"Follow one ride request.",copy:"Search narrows quickly; dispatch then crosses the consistency boundary.",steps:[["Rider","0ms",0],["Geo cells","8ms",8],["Freshness","4ms",4],["Approx ETA","18ms",18],["Rank","3ms",3],["Reserve","12ms",12],["Push offer","15ms",15]]},
failures:[{signal:"consumer lag",title:"Index updater lags",effect:"Drivers appear in old cells.",mitigation:"Rebuild from latest store and expand fallback search."},{signal:"hot cell",title:"Airport spike",effect:"One shard saturates.",mitigation:"Logical subshards, read fanout, city isolation."},{signal:"ETA timeout",title:"Routing overload",effect:"Ranking misses deadline.",mitigation:"Fallback to approximate ETA or distance."},{signal:"lease conflict",title:"Driver already reserved",effect:"Top choice is unavailable.",mitigation:"Expected CAS failure; try next candidate."}],
final:{copy:"The location plane is eventually consistent and write-heavy. Dispatch applies narrow strong consistency only when reserving supply.",primary:[["Driver apps","network"],["Gateways","network"],["Event stream","data"],["Latest state","storage"],["Cell index","data"],["Nearby query","compute"],["ETA rank","compute"],["Dispatch lease","storage"]],support:["Rider API","Traffic tiles","Trip service","Push","Supply forecast","Fraud","Observability"],tradeoffs:[["LOCATION","Eventual + TTL","Scales fast writes; a few seconds stale."],["RESERVE","Conditional strong write","Prevents double dispatch."],["SEARCH","Adaptive cell rings","Bounds latency; may omit far candidates."]]},
interview:[["Why not PostGIS for every request?","It can start there, but millions of updates and hotspots favor a materialized in-memory cell index."],["How choose cell size?","Balance drivers per cell, neighbor reads, update churn, and density using hierarchy."],["How does a driver disappear?","Availability change or expired location/session lease removes it; repair handles missed deletes."],["Why rank twice?","Cheap ETA prunes; precise routing for top candidates preserves quality in budget."]],
quiz:[{question:"Where is strong consistency required?",options:["Every GPS update","Driver reservation","Supply dashboard"],answer:1,explain:"Reservation prevents two rides from claiming one driver."},{question:"Why TTL locations?",options:["Compress maps","Remove silent drivers","Increase GPS"],answer:1,explain:"A missed heartbeat must expire availability."}],
complete:{title:"Nearby matching is <b>ephemeral geo state plus precise reservation.</b>",takeaways:["Location streams","Latest state","Geo cells","Ring search","ETA ranking","Leases","Hotspots"]}
},

"google-search":{number:7,plainTitle:"Web Search Engine",title:"Design a <span>Web Search Engine</span>",category:"Search Infrastructure",difficulty:"Expert",prompt:"Design a web-scale search engine that discovers pages, builds a distributed index, retrieves candidates, and ranks results in a fraction of a second.",concepts:["Crawler","URL frontier","Inverted index","Index shards","Ranking","Freshness","Spam"],
requirements:{note:"Focus on crawl → process → index → retrieve → rank → serve.",functional:["Discover and fetch public pages","Extract text, links, and metadata","Return relevant ranked results","Refresh changed and remove dead pages"],nonfunctional:["Sub-second query latency","Massive index scale and availability","Fresh important pages quickly","Resist duplicate and malicious content"],assumptions:[["CORPUS","100B documents","Petabytes of index data"],["QUERIES","100K/s peak","Global short reads"],["SLO","P99 < 500ms","End-to-end result assembly"],["CRAWL","Billions / day","Politeness constrains fetches"]]},
estimates:{items:[{label:"DOCUMENTS",value:"100B",detail:"corpus"},{label:"QUERY",value:"100K/s",detail:"peak"},{label:"INDEX",value:"PB scale",detail:"compressed"},{label:"RESULTS",value:"10",detail:"from thousands"}],formula:"An inverted index turns a term into a <b>compressed posting list of matching document IDs</b>, avoiding corpus scans."},
naive:{title:"Store pages and scan all text per query.",copy:"One crawler saves HTML; search runs contains(query) across every page.",nodes:["Crawler","Page DB","Full scan"],breaks:["Query cost grows with corpus","Crawler loops and ignores politeness","Term count ranks poorly","Updates require rescanning","One server cannot hold the web"]},
evolution:[
{title:"Control crawling",problem:"The web is cyclic and independently owned.",explain:"A frontier deduplicates and schedules per-host requests under robots/politeness.",solution:"URL frontier",nodes:[["Seeds","data"],["Frontier","data"],["Fetchers","network"],["Raw store","storage"]]},
{title:"Process documents",problem:"HTML contains boilerplate, duplicates, redirects, and links.",explain:"Parsers emit normalized text, identity, metadata, and link graph.",solution:"Processing pipeline",nodes:[["Raw pages","storage"],["Parser","compute"],["Canonicalizer","compute"],["Docs","storage"]]},
{title:"Build inverted indexes",problem:"Scanning documents cannot meet query latency.",explain:"Indexers map terms to compressed postings and ranking signals.",solution:"Index builder",nodes:[["Docs","storage"],["Indexer","compute"],["Segments","data"]]},
{title:"Shard serving",problem:"The full index does not fit one machine.",explain:"Document shards retrieve local top candidates in parallel.",solution:"Index serving fleet",nodes:[["Query","network"],["Broker","compute"],["Index shards","data"],["Top-K merge","compute"]]},
{title:"Retrieve then rank",problem:"Expensive scoring cannot touch every match.",explain:"Cheap retrieval narrows; progressively richer rankers score fewer candidates.",solution:"Multi-stage ranking",nodes:[["Candidates","data"],["L1 rank","compute"],["L2 rank","compute"],["Results","network"]]},
{title:"Publish freshness",problem:"Pages change during long full builds.",explain:"Small incremental segments publish quickly and merge later.",solution:"Realtime index segments",nodes:[["Change crawl","network"],["Realtime index","data"],["Merger","compute"],["Serving index","data"]]}
],
components:[
{name:"URL Frontier",type:"CRAWL SCHEDULER",summary:"Owns which URL may be fetched next and when.",input:"canonical URL + priority",output:"host-safe fetch task",internals:"Deduplicates fingerprints, maintains per-host queues, next-allowed time, robots rules, and freshness priority.",ops:"Checkpoint queues, cap host depth, detect traps, and version robots decisions.",without:"Crawlers hammer sites, revisit duplicates, and enter infinite calendars.",tradeoff:"Politeness slows freshness; prioritization biases coverage."},
{name:"Fetcher",type:"DISTRIBUTED NETWORK",summary:"Downloads pages safely and records response metadata/content.",input:"URL task",output:"status + headers + body",internals:"Resolves DNS, follows bounded redirects, enforces size/time limits, and fingerprints bytes.",ops:"Sandbox, block private-network targets, back off by host, and log failures.",without:"There is no fresh corpus.",tradeoff:"Network and dynamic content make fetches nondeterministic."},
{name:"Canonicalizer",type:"DOCUMENT IDENTITY",summary:"Maps URL variants and duplicate pages to stable document identities.",input:"URL + redirects + fingerprints",output:"canonical doc ID",internals:"Normalizes host/path, removes known trackers, follows canonical hints, and clusters near duplicates.",ops:"Audit rules; mistaken canonicalization can erase distinct pages.",without:"Duplicates fill the index and split ranking signals.",tradeoff:"Aggressive rules merge real pages; conservative rules waste space."},
{name:"Document Processor",type:"CONTENT PIPELINE",summary:"Extracts visible text, fields, language, links, structured data, quality, and safety signals.",input:"raw response",output:"normalized document",internals:"Parses DOM, removes boilerplate, tokenizes by language, and emits link edges.",ops:"Version processors and reprocess immutable raw pages without recrawling.",without:"Indexes store markup noise and lack structure.",tradeoff:"Parsing untrusted HTML is CPU-heavy and risky."},
{name:"Inverted Index Builder",type:"INDEX CONSTRUCTION",summary:"Creates term → postings structures optimized for retrieval.",input:"terms + document signals",output:"immutable compressed segments",internals:"Sorts term/doc pairs, delta-encodes IDs, stores frequency/positions, and writes lexicon skips.",ops:"Checksum, distribute, canary, then atomically activate segment generations.",without:"Every query scans page bodies.",tradeoff:"Indexing duplicates data and requires merge work."},
{name:"Query Broker",type:"DISTRIBUTED FANOUT",summary:"Parses a query, calls index shards, and merges local top-K.",input:"query + locale/context",output:"global candidates",internals:"Normalizes/spell-corrects, selects tiers, applies deadlines, fans out, and heap-merges scores.",ops:"Hedge slow shards, permit partial results, and cache popular queries carefully.",without:"Clients must know topology and cannot combine the corpus.",tradeoff:"Fanout multiplies QPS and exposes tail latency."},
{name:"Index Shard",type:"ONLINE RETRIEVAL",summary:"Searches one document partition using compressed postings.",input:"parsed query + deadline",output:"local top-K",internals:"Intersects postings, applies field boosts, early termination, and cheap first-stage scoring.",ops:"Replicate, memory-map hot structures, prefetch postings, and monitor hot terms.",without:"No scalable corpus-search primitive exists.",tradeoff:"Document sharding queries many shards."},
{name:"Ranking Pipeline",type:"ONLINE RELEVANCE",summary:"Scores candidates with lexical, semantic, quality, freshness, and context features.",input:"query + candidates",output:"ordered safe results",internals:"L1 ranks thousands cheaply, L2 scores hundreds richly, then policy/diversity processes the final set.",ops:"Budget each stage, provide default features, shadow releases, and roll back quickly.",without:"Word matches fail intent, quality, or safety.",tradeoff:"Models add latency, opacity, dependencies, and feedback loops."}
],
deepDives:[
{title:"Inverted index internals",summary:"A read-optimized projection of the corpus.",steps:["Assign integer document IDs.","Emit term, doc, frequency, positions, and fields.","Sort then delta-encode IDs into compressed blocks.","Use skip/block-max data to avoid hopeless postings."],decision:"Immutable compressed segments make serving fast and publication safe."},
{title:"Distributed top-K",summary:"Each shard sees only part of the corpus.",steps:["Ask every selected shard for more than final K.","Return scores and compact features.","Heap-merge and deduplicate canonical clusters.","Rerank a much smaller global set."],decision:"Over-fetch locally enough to preserve global candidates."},
{title:"Freshness versus compactness",summary:"Optimized builds are slow; news must appear quickly.",steps:["Publish fresh docs in small incremental segments.","Query base plus increments.","Merge segments and drop obsolete versions.","Atomically switch serving manifest."],decision:"Use immutable LSM-like segments: publish now, compact later."}
],
trace:{title:"Follow one search query.",copy:"Parallel retrieval dominates; richer ranking touches fewer documents.",steps:[["Query edge","8ms",8],["Parse","6ms",6],["Fanout","3ms",3],["Retrieve","55ms",55],["Merge","8ms",8],["ML rank","42ms",42],["Render","18ms",18]]},
failures:[{signal:"shard timeout",title:"Index replica is slow",effect:"Global results wait or lose coverage.",mitigation:"Deadline, hedged replica, partial-result policy."},{signal:"frontier growth",title:"Crawl trap",effect:"Useless URL permutations consume budget.",mitigation:"Pattern budgets, fingerprints, host caps."},{signal:"checksum",title:"Bad index publication",effect:"Queries crash or miss documents.",mitigation:"Canary activation, immutable generation rollback."},{signal:"feature timeout",title:"Rank dependency fails",effect:"Rich ranker misses deadline.",mitigation:"Default features and lexical fallback."}],
final:{copy:"An asynchronous crawl/index plane produces immutable generations. A latency-bounded query plane fans out retrieval and progressively ranks candidates.",primary:[["Users","network"],["Query edge","network"],["Broker","compute"],["Index replicas","data"],["Top-K merge","compute"],["Ranking","compute"],["Results","network"]],support:["URL frontier","Fetcher fleet","Raw store","Document processor","Index builder","Link graph","Spam / safety","Realtime segments"],tradeoffs:[["SHARDING","By document","Simple scoring; fanout to shards."],["FRESHNESS","Incremental segments","Fast visibility; merge overhead."],["FAILURE","Partial results","Better latency; recall may fall."]]},
interview:[["Why an inverted index?","It retrieves matching document IDs without scanning bodies, using compressed postings optimized for intersection."],["How do deletions work?","Publish tombstones or live-doc bitmaps immediately; remove postings during compaction."],["How handle a slow shard?","Hedge to a replica, enforce deadlines, and optionally return partial results."],["Where does semantic search fit?","Vector retrieval can add candidates or embeddings can rank; combine with lexical signals."]],
quiz:[{question:"Why over-fetch top-K per shard?",options:["Crawl faster","Preserve global candidates","Reduce documents"],answer:1,explain:"Local rank does not equal global rank after merge."},{question:"How do fresh pages appear quickly?",options:["Incremental segments","Restart shards","Scan HTML"],answer:0,explain:"Small segments publish quickly and merge later."}],
complete:{title:"Search is <b>asynchronous knowledge construction</b> plus bounded ranking.",takeaways:["Polite crawling","Canonical identity","Document processing","Inverted index","Shard fanout","Multi-stage ranking","Freshness"]}
}
};
